spring.datasource.url=jdbc:postgresql://localhost:5432/auth_db
spring.datasource.username=postgres
spring.datasource.password=admin

spring.jpa.show-sql=true

jwt.secret=mysupersecretkeymysupersecretkey12345
jwt.expiration=900000

google.clientId=345365455615-aof5cgb5dt4ddu2hquuc4eosh7bq5lam.apps.googleusercontent.com