server.port=${PORT:8081}

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.show-sql=false

jwt.private-key=${JWT_PRIVATE_KEY}
jwt.public-key=${JWT_PUBLIC_KEY}
jwt.expiration=900000

google.clientId=${GOOGLE_CLIENT_ID}

resend.api-key=${RESEND_API_KEY}
app.base-url=${APP_BASE_URL}