# App Name
spring.application.name=authservice

# Server
server.port=8081

# Database (PostgreSQL)
spring.datasource.url=jdbc:postgresql://localhost:5432/auth_db
spring.datasource.username=postgres
spring.datasource.password=admin

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# JWT (we will use this later)
jwt.secret=mysecretkey123
jwt.expiration=900000